Add support for `ansi` colors and add `.ansi256ToAnsi()`, `.rgbToAnsi()` and `.hexToAnsi()`
chalk/ansi-styles pull request #71
Opened 2021-04-19 12:33 UTC by Richienb

https://github.com/chalk/chalk/pull/433#issuecomment-822089880

2021-04-20 06:47 UTC, sindresorhus approved these changes

2021-04-20 06:47 UTC, sindresorhus commented
@Qix- LGTY?

2021-04-20 17:30 UTC, Qix- requested changes
A few nits

2021-04-20 17:30 UTC, Qix- commented on readme.md
> +## [16 / 256 / 16 million (TrueColor) support](https://gist.github.com/XVilka/8346728)
```suggestion
## 16 / 256 / 16 million (TrueColor) support
```

2021-04-20 17:30 UTC, Qix- commented on readme.md
> +`ansi-styles` allows converting between various color formats and ANSI escapes, with support for 16, 256 and 16 million colors.
```suggestion
`ansi-styles` allows converting between various color formats and ANSI escapes, with support for 16, 256 and [16 million colors](https://gist.github.com/XVilka/8346728).
```

2021-04-20 17:30 UTC, Qix- commented on index.js
> +					green = Math.floor((code % 36) / 6) / 5;
```suggestion
					green = Math.floor(remainder / 6) / 5;
```

2021-04-21 00:05 UTC, Richienb commented
The CI is yet to have cached a version of `@babel/traverse` released 44 minutes ago so it is currently failing as of now.

2021-04-21 05:01 UTC, Qix- commented
Can we get some tests for `ansi256To16` specifically?

2021-04-21 05:08 UTC, Richienb commented
> Can we get some tests for `ansi256ToAnsi` specifically?
> 
> Otherwise, LGTM. Thanks for the heads up about the failing test.

Since this function is being added to `color-convert` (https://github.com/Qix-/color-convert/issues/92) it should really be tested there. That's why there aren't any tests here for rgb → ansi256.

2021-04-21 08:48 UTC, merged

2021-04-21 09:43 UTC, Qix- commented
I disagree, but okay. Chalk does not rely on color convert any longer so their testing concerns no longer overlap. If you're going to vendor code, you should include automated tests in the destination codebase, IMO.

2021-04-21 09:48 UTC, Richienb commented
If it's a direct copy-paste from the original codebase that is already tested, then IMO unit tests aren't nessessary. Now would be the time to add the short-circut to `color-convert`.

2021-04-21 09:49 UTC, sindresorhus commented
Sorry, I missed the comment about tests. I agree we should have some tests here too.