take care of hermes javascript engine
chalk/ansi-styles pull request #78
Opened 2021-11-04 16:34 UTC by ice6

It is sad that hermes do not support regex named group.

https://github.com/facebook/hermes/blob/main/doc/RegExp.md

same issue others encountered as me :)

https://github.com/facebook/hermes/issues/89

because this library is so foundamental and small, it will be a pleasure if this library can do the favor.

:)

2021-11-04 17:49 UTC, Qix- requested changes
I don't normally care to support non-compliant javascript engines but in this case the change makes sense. Named groups and destructuring is unnecessary here and only burns cycles anyway.

Just one change from me.

2021-11-04 17:49 UTC, Qix- commented on index.js
> +				const matches = /([a-f\d]{6}|[a-f\d]{3})/i.exec(hex.toString(16));
```suggestion
				const matches = /[a-f\d]{6}|[a-f\d]{3}/i.exec(hex.toString(16));
```

2021-11-05 01:21 UTC, sindresorhus commented
While this is a seemingly simple change, it's a slippery slope. Hermes only supports ES6, so this issue will be hit again in the future.

2021-11-05 02:30 UTC, ice6 commented
> While this is a seemingly simple change, it's a slippery slope. Hermes only supports ES6, so this issue will be hit again in the future.

It will be ok to me if you add me as a maintainer of this little library. :)

2021-11-07 07:36 UTC, ice6 commented
for those suffering such little problem, now I recommend https://www.npmjs.com/package/patch-package.
as the package claimed, it is indeed a savior.

2021-11-07 07:36 UTC, closed without merging

2022-03-03 06:55 UTC, bombillazo commented
> for those suffering such little problem, now I recommend https://www.npmjs.com/package/patch-package. as the package claimed, it is indeed a savior.

What would be the solution using patch-package? What is the patch required to remove the named group?